### ISSUE TITLE
Fanart and Poster are not shown in Lovelace UI

### ISSUE THREAD

**Issue by murmelbahn** [custom-components/sensor.kodi_recently_added#1]
**Describe the Bug**
I dont see any images of the upcoming medias. No poster and no fanart but they are included in my kodi library.

**Home Assistant Version**
0.87.0

**Screenshots**
https://imgur.com/mlfNQlu

**Additional Context**
Here are the data of the sensor:

data: [{"title_default": "$title", "line1_default": "$genres", "line2_default": "$release", "line3_default": "$rating - $runtime", "line4_default": "$studio", "icon": "mdi:arrow-down-bold"}, {"aired": "2018-10-24", "airdate": "2019-02-03T12:44:52Z", "flag": true, "genres": "Drama,Musik", "rating": "\u2605 8.2", "release": "$date", "runtime": 135, "title": "Bohemian Rhapsody", "studio": "GK Films,Regency Enterprises,Queen Films,Tribeca Productions,New Regency Pictures,20th Century Fox", "fanart": "media/3TB1/Filme/Bohemian Rhapsody (2018)/fanart.jpg", "poster": "media/3TB1/Filme/Bohemian Rhapsody (2018)/poster.jpg"}, {"aired": "2018-09-28", "airdate": "2018-12-06T22:20:07Z", "flag": true, "genres": "Science Fiction,Action", "rating": "\u2605 6.6", "release": "$date", "runtime": 112, "title": "Venom", "studio": "Avi Arad Productions,Matt Tolmach Productions,Pascal Pictures,Marvel Entertainment,Tencent Pictures", "fanart": "media/3TB1/Filme/Venom (2018)/fanart.jpg", "poster": "media/3TB1/Filme/Venom (2018)/poster.jpg"}, {"aired": "1988-04-16", "airdate": "2018-11-21T15:01:05Z", "flag": true, "genres": "Fantasy,Zeichentrick,Familie", "rating": "\u2605 8.1", "release": "$date", "runtime": 86, "title": "Mein Nachbar Totoro", "studio": "Studio Ghibli,Nibariki,Tokuma Japan Communications Co. Ltd.", "fanart": "media/3TB1/Filme/Mein Nachbar Totoro (1988)/fanart.jpg", "poster": "media/3TB1/Filme/Mein Nachbar Totoro (1988)/poster.jpg"}, {"aired": "2018-07-13", "airdate": "2018-11-20T16:06:50Z", "flag": true, "genres": "Action,Thriller,Abenteuer", "rating": "\u2605 7.3", "release": "$date", "runtime": 148, "title": "Mission: Impossible - Fallout", "studio": "Paramount,Bad Robot,Skydance Media,TC Productions,Alibaba Pictures Group"

**Comment by boralyl** [comment]
Thanks for reporting!  I actually have a similar issue, but I'm not sure how this should be handled.  It appears that it depends on how kodi is processing and saving the artwork.  It appears your artwork is being saved locally to disk.  My similar issue is some of my artwork is on my nas and homeassisant isn't able to load it from `nfs://my-ip/image.jpg`.  

I'm not entirely sure how Kodi decides this as some of my media does have images due to the fanart/poster being stored as an external link, e.g. `http://image.tmdb.org/t/p/original/9TUXAXQ3SEyykLdW2nzGpKZtPn9.jpg`

I'll have to do some research to see if there is a way to resolve this as the component will only show artwork if they are external links, not an nfs url or a local path to the media.

**Comment by gkron92** [comment]
I'm having this issue as well.  When I first load in the movie to my library it works fine displaying the image but if it gets touched again it won't display the image anymore.  If I reload the movie into the library or if I update the artwork using artwork beef for example it won't display the image anymore.  I'm using a NAS and nfs as well

**Comment by boralyl** [comment]
I don't have a good solution for this particular issue.  If the artwork url stored in your kodi database points to a file on your NAS using a nfs url or simply a file on your local disk it can't display the image in home assistant as there is no way to access it.

Maybe it's possible if you enable the web UI?  I'll have to take a look at how kodi serves images when that is enabled.

**Comment by gkron92** [comment]
Well I'm running home assistant in docker on the same NAS that stores the Kodi images.  Can the image once you scan it into your library be copied to an HA folder and access it that way.  It works the first time I scan the movie into my library.  What do you mean by enable web UI?

**Comment by boralyl** [comment]
I was referring to: https://kodi.wiki/view/Web_interface

**Comment by gkron92** [comment]
Gotcha.  If I can help in any way let me know.

**Comment by gkron92** [comment]
How does Kodi serve images when you first add a movie to the library?  Does it temporarily store it correctly?

**Comment by boralyl** [comment]
@murmelbahn Could you try the latest version and let me know if it fixed the artwork?

@gkron92 I just released v0.2.7.  I verified that artwork that has an nfs url will now load properly, e.g. `nfs://10.10.1.11/path/tv/Veronica Mars/fanart.jpg`  Let me know if this works for you.

Note that I think this will only work if you have enabled the kodi web interface.

**Comment by boralyl** [comment]
> How does Kodi serve images when you first add a movie to the library? Does it temporarily store it correctly?

It's not that it is not stored correctly.  It's just that the path to the artwork can be in various formats (path to local file on kodi (`media/fanart.jpg`), url (`https://tvshows.com/ncis.jpg`), nfs (`nfs://10.1.1.1/path/to/art/fanart.jpg`), etc.)  If the path is not a url, HA can't load it as it doesn't know about local files on your kodi device or your nas.  

What I did was figured out the url kodi uses for images when you are browsing the web interface and I convert the artwork to those url's if the artwork isn't already a normal url.

**Comment by gkron92** [comment]
You did it.  Well done.  Thanks!

**Comment by gkron92** [comment]
Is it possible for the Kodi sensor to pull in animated posters and fanart?  I save mine as poster.gif in the movie folder.  Would be awesome to have these displayed in HA instead of the .jpg if one is available

**Comment by boralyl** [comment]
You can try it out by modifying the database and have the fanart or poster point to the gif you've got., but for simplicity this component will only pull artwork from whatever file the db reports in the fanart or poster fields.

**Comment by gkron92** [comment]
Hi Adam,

The fix for nfs located files only works when I am on my home network.  If accessing over the internet from a different location it doesn’t work.  The images go back to missing again.  Any idea what is going on?

Thanks

Gary

**Comment by boralyl** [comment]
Could you open up a new issue?  The reason is that it's trying to access your local ip where kodi is running which isn't exposed to the Internet.  I believe the sonarr and radarr components download the images locally and cache them in your homeassistant instance.

**Comment by gkron92** [comment]
Sure and no idea why I called you Adam.  Sorry about that.
