### ISSUE TITLE
Issues with Upcoming 0.91 of HA0.115.2

### ISSUE THREAD

**Issue by fontes31** [custom-components/sensor.kodi_recently_added#10]
Hi,

After updating my HA to 0.115.2 i have this error:

"Platform error sensor.kodi_recently_added - No module named 'homeassistant.components.media_player.kodi'"

my config:

- platform: kodi_recently_added
    host: 192.168.1.118
    port: 8080
    tcp_port: 9090

**Comment by fontes31** [comment]
i saw that was reported before. Can close it

**Comment by boralyl** [comment]
See #9

**Comment by boralyl** [comment]
Fix is in the works!
