### ISSUE TITLE
TransportError?

### ISSUE THREAD

**Issue by imbaimbaimba** [custom-components/sensor.kodi_recently_added#2]
Hi, anyone know what the below is coming from?

TransportError trying to run API method None.VideoLibrary.GetRecentlyAddedEpisodes({'properties': ['art', 'dateadded', 'episode', 'fanart', 'firstaired', 'playcount', 'rating', 'runtime', 'season', 'showtitle', 'title']})

File "/home/homeassistant/.homeassistant/custom_components/sensor/kodi_recently_added.py", line 100, in async_update
self.data = result['episodes']
TypeError: 'NoneType' object is not subscriptable

**Comment by boralyl** [comment]
Thanks for reporting!  To resolve this, if there is a transport error getting data from Kodi the code will skip updating the sensor until the next run instead of causing a `TypeError`.  Fix on develop and will be in v0.2.1
