### ISSUE TITLE
Lovelace requires http authentication

### ISSUE THREAD

**Issue by wojtek14a** [custom-components/sensor.kodi_recently_added#7]
When opening the lovelace view with the **Upcoming Media Card** fed by `kodi_recentyl_added` there sometimes is a browser prompt requesting a http authentication to kodi web interface. After entering credential, card is populated with fanart pictures in the background. 

Is it possible to implement some kind of a cache for a sensor to download fanart in advance so that the browser doesn't ask for credentials I've already provided in the sensor config? Or maybe it is possible to automatically pass those saved credentials in the background each time the browser requires them, so that it is invisible for the user?

**Comment by boralyl** [comment]
I know you can put the basic auth in the url like `http://user:password@10.0.1.1/images/some_tv_show.jpg`, but not entirely sure if that would work or not.  Additionally I'm not certain if you can obtain the credentials if you setup the integration via the UI as is now the preferred way as of 0.115.  Defining credentials in the `configruation.yaml` is now deprecated for the kodi component.

I did a quick search through the code in home-assistant core and didn't see anything obvious that currently caches files to disk, but that may be the best option.  It's hard to say what best practice would be for writing images to disk with different setups that ephemeral like docker and hassio.

**Comment by boralyl** [comment]
I re-wrote this component and think this issue is now resolved.  The new version isn't available in HACS yet, but if you wanted to try it out in advance it can be found here: https://github.com/boralyl/kodi-recently-added  

It was moved to a new repository and now requires HA >= 0.115.0.  The configuration changed as well and kodi must be setup through the integrations UI.

**Comment by boralyl** [comment]
This should be fixed now in the new component.  Please re-open the issue in that repo if that is not the case. https://github.com/boralyl/kodi-recently-added
