### ISSUE TITLE
115.1: No module named 'homeassistant.components.media_player.kodi'

### ISSUE THREAD

**Issue by themeatsweats** [custom-components/sensor.kodi_recently_added#9]
Good afternoon. Getting the following errors as of 115.1 (maybe on 115.0 as well). 

`Platform error sensor.kodi_recently_added - No module named 'homeassistant.components.media_player.kodi'`

```
Log Details (ERROR)
Logger: homeassistant.components.homeassistant
Source: components/homeassistant/__init__.py:113
Integration: Home Assistant (documentation, issues)
First occurred: 4:20:44 PM (1 occurrences)
Last logged: 4:20:44 PM

Platform error sensor.kodi_recently_added - No module named 'homeassistant.components.media_player.kodi' Platform error sensor.kodi_recently_added - No module named 'homeassistant.components.media_player.kodi'
```

Installed component via HACS and yaml is simply:
```
  - platform: kodi_recently_added
    username: user
    password: pass
    host: 192.168.1.x
```
media_player.kodi is a valid entity as shown in dev tools and I do have control and data on it. I believe some significant work was done on media.players in 115, so assuming that has something to do with it.

**Comment by 4841penoyer** [comment]
So looks like I picked a fun day to try and get this to work.  I'm having the same issue but I've been trying to use the entity_id variant, but the username/password fails as well.

**Comment by boralyl** [comment]
I had noticed there were some breaking changes in regards to kodi in the release notes.  I'm upgrading my HA instance this weekend so I can figure out what's breaking and get a fix for this released.  It seems like the platform variation is going to be deprecated so going forward you will likely want to use the UI to configure kodi.

**Comment by boralyl** [comment]
Took a quick look this morning and I see some imports changed and some constants and classes were renamed.  Beyond that the way the connection is setup changed as well.  I started making individual changes, but it's a bit of a mess at the moment.

Since this is the first custom component I wrote, I did a lot of things wrong with the initial implementation.  I think rather than try to fix the existing code, I'm going to do a rewrite of this component since it's just 2 sensors.  With that being said a fix for this will probably take a few weeks but it's in progress.

**Comment by boralyl** [comment]
It's not yet available in HACS, but if you wanted to try out the updated version that works with >= 0.115.x you can manually install the updated version found here: https://github.com/boralyl/kodi-recently-added

**Comment by themeatsweats** [comment]
Still getting an error (see below). Container is on docker using host networking, set up the Kodi integration from the UI after deleting the previous entries. 

config.yaml:
```
sensor:

  - platform: kodi_recently_added
    host: xbmctheater
```

error in HA:
```
Log Details (ERROR)
Logger: custom_components.kodi_recently_added.sensor
Source: custom_components/kodi_recently_added/sensor.py:37
Integration: Kodi Recently Added Media (documentation, issues)
First occurred: 6:06:08 PM (1 occurrences)
Last logged: 6:06:08 PM

Failed to setup sensor. Could not find config entry for kodi host xbmctheater
```

**Comment by boralyl** [comment]
Did you use `xbmctheater` as the host when configuring via the UI?  It's looking for a matching host from what you have setup.  I can verify that it's working for me locally.

You could try adding a log right above line 25 to see what's setup.  Something like:

```python
_LOGGER.warning("config entry data: %s", entry.data)
```

It should show at least one entry with a host/port/username/password/ssl keys.

**Comment by boralyl** [comment]
One other thing I recalled when I was testing this out.  I needed to first remove the entry for kodi from my configuration.yaml, then restart HA.  After that, I went into the integrations and deleted any existing kodi integrations.  Then I re-added my kodi host, added the kodi_recently_added platform to my configuration.yaml and restarted HA once more.

**Comment by maheus** [comment]
fix ok with your github realese

thanks @boralyl

**Comment by themeatsweats** [comment]
> Did you use `xbmctheater` as the host when configuring via the UI? It's looking for a matching host from what you have setup. I can verify that it's working for me locally.
> 
> You could try adding a log right above line 25 to see what's setup. Something like:
> 
> ```python
> _LOGGER.warning("config entry data: %s", entry.data)
> ```
> 
> It should show at least one entry with a host/port/username/password/ssl keys.

Yes, that is the correct host. I removed the previously installed kodi integration and custom component, restarted, installed the new component via HACS and custom repository, added the config.yaml entry, and restarted again. No luck.

I did however just get this working by changing the config and UI kodi entries to their respective IPs instead of hostname. This hostname resolves everywhere else, so assuming the CC is working for you guys it might just be a docker networking issue on my side (container is using host network).

**Comment by boralyl** [comment]
T

> > Did you use `xbmctheater` as the host when configuring via the UI? It's looking for a matching host from what you have setup. I can verify that it's working for me locally.
> > You could try adding a log right above line 25 to see what's setup. Something like:
> > ```python
> > _LOGGER.warning("config entry data: %s", entry.data)
> > ```
> > 
> > 
> > It should show at least one entry with a host/port/username/password/ssl keys.
> 
> Yes, that is the correct host. I removed the previously installed kodi integration and custom component, restarted, installed the new component via HACS and custom repository, added the config.yaml entry, and restarted again. No luck.
> 
> I did however just get this working by changing the config and UI kodi entries to their respective IPs instead of hostname. This hostname resolves everywhere else, so assuming the CC is working for you guys it might just be a docker networking issue on my side (container is using host network).

That's very possible that the host is being resolved to IP and it's being stored.  I added all configured hosts in the error message so it should be easier to spot.

**Comment by themeatsweats** [comment]
Interesting. Changed back to hostnames, sprinkled in some restarts, no other changes, and now it's working fine. /shrug

I'll keep you updated if that changes. Thanks for the responsiveness and quick fix!

**Comment by boralyl** [comment]
That's great to hear!  Going to keep this issue open until the new repo is accepted as a default in HACS.

**Comment by boralyl** [comment]
Going ahead and closing this before archiving the repo.  New repo is located at https://github.com/boralyl/kodi-recently-added
